// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// Information describing a single media input or output device.
class MediaDeviceInfo {
  /// Unique identifier for the represented device.
  final String deviceId;

  /// Kind of the represented device.
  final MediaDeviceKind kind;

  /// Label describing the represented device.
  final String label;

  /// Native sample rate in `Hz`.
  ///
  /// For audio devices only. [`None`] for video or if is unavailable.
  final int? sampleRate;

  /// Number of channels.
  ///
  /// For audio devices only. [`None`] for video or if is unavailable.
  final int? numChannels;

  /// Platform container ID (physical device identifier).
  ///
  /// For audio devices only. [`None`] for video or if is unavailable.
  final String? containerId;

  const MediaDeviceInfo({
    required this.deviceId,
    required this.kind,
    required this.label,
    this.sampleRate,
    this.numChannels,
    this.containerId,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      kind.hashCode ^
      label.hashCode ^
      sampleRate.hashCode ^
      numChannels.hashCode ^
      containerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaDeviceInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          kind == other.kind &&
          label == other.label &&
          sampleRate == other.sampleRate &&
          numChannels == other.numChannels &&
          containerId == other.containerId;
}

/// Possible kinds of media devices.
enum MediaDeviceKind {
  /// Audio input device (for example, a microphone).
  audioInput,

  /// Audio output device (for example, a pair of headphones).
  audioOutput,

  /// Video input device (for example, a webcam).
  videoInput,
}

/// Information describing a display.
class MediaDisplayInfo {
  /// Unique identifier of the device representing the display.
  final String deviceId;

  /// Title describing the represented display.
  final String? title;

  const MediaDisplayInfo({required this.deviceId, this.title});

  @override
  int get hashCode => deviceId.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaDisplayInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          title == other.title;
}
